name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Remix app
        run: npm run build # Replace with your build command

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy # Replace with your deploy command
          echo "Deployed to GitHub Pages"

